# Generated by Django 5.2.4 on 2025-07-10 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_travel_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='passenger',
        ),
        migrations.AddField(
            model_name='passenger',
            name='booking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.booking'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
