# Generated by Django 5.2.4 on 2025-07-11 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_booking_passenger_passenger_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='booking.booking'),
        ),
    ]
